/**
 * Pre-generates the Swagger spec as a TypeScript module so it can be imported
 * directly by the app at runtime.
 *
 * WHY a .ts file instead of .json?
 *   @vercel/node bundles the codebase with ncc, which compiles and inlines TypeScript
 *   modules. tsc (used for local/CI builds) compiles .ts → .js in dist/ but does NOT
 *   copy .json files. Exporting the spec as a TypeScript module means both bundling
 *   strategies always find the file at the expected path.
 *
 * Run whenever JSDoc annotations change:
 *   npm run generate-swagger
 */
import swaggerJSDoc from "swagger-jsdoc";
import fs from "fs";
import path from "path";

const options: swaggerJSDoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: { title: "Artiste Meetup API", version: "1.0.0" },
    // Relative URL works on localhost in dev AND the Vercel domain in production
    servers: [{ url: "/api/v1" }],
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  // Relative to cwd (project root) so glob expands correctly on all platforms
  apis: [
    "src/routes/*.ts",
    "src/modules/**/*.route.ts",
    "src/modules/**/*.dto.ts",
  ],
};

const spec = swaggerJSDoc(options);

// Write as a TypeScript module so tsc compiles it and ncc bundles it correctly.
const tsContent = `// Auto-generated by: npm run generate-swagger
// Do not edit manually — re-run the script whenever JSDoc annotations change.
/* eslint-disable */
export default ${JSON.stringify(spec, null, 2)} as object;\n`;

const outputPath = path.join(__dirname, "../swagger-spec.ts");
fs.writeFileSync(outputPath, tsContent);
console.log(`✓ Swagger spec written to ${outputPath}`);
