// Swagger spec is pre-generated by: npm run generate-swagger
// Committing the JSON means @vercel/node bundles it into the deployment,
// so it's always available at runtime regardless of how files are packaged.
// Re-run the generate script whenever JSDoc annotations are added or changed.
import spec from "../swagger-spec.json";

export default spec as object;
