// Swagger spec is pre-generated by: npm run generate-swagger
// Importing as a TypeScript module (not JSON) ensures tsc compiles it into dist/
// and @vercel/node (ncc) bundles it — so the spec is always available at runtime
// regardless of how the project is packaged.
// Re-run the generate script whenever JSDoc annotations are added or changed.
import spec from "../swagger-spec";

export default spec;
