// Auto-generated by: npm run generate-swagger
// Do not edit manually — re-run the script whenever JSDoc annotations change.
/* eslint-disable */
export default {
  "openapi": "3.0.0",
  "info": {
    "title": "Artiste Meetup API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/api/v1"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "DashboardResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "bookings": {
                "type": "object",
                "properties": {
                  "total": {
                    "type": "integer"
                  },
                  "pending": {
                    "type": "integer"
                  },
                  "confirmed": {
                    "type": "integer"
                  },
                  "rejected": {
                    "type": "integer"
                  },
                  "cancelled": {
                    "type": "integer"
                  }
                }
              },
              "chats": {
                "type": "object",
                "properties": {
                  "active": {
                    "type": "integer"
                  },
                  "recentActive": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/ChatObject"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "RegisterDto": {
        "type": "object",
        "description": "Request body for all three registration endpoints. The role is determined by the endpoint called, not this body.\n",
        "required": [
          "name",
          "email",
          "password"
        ],
        "properties": {
          "name": {
            "type": "string",
            "example": "Ada Okafor"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "ada@example.com"
          },
          "password": {
            "type": "string",
            "minLength": 6,
            "example": "mypassword123"
          }
        }
      },
      "RegisterResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 201
          },
          "message": {
            "type": "string",
            "example": "Registration successful. Check your email for a 6-digit OTP."
          },
          "data": {
            "type": "object",
            "properties": {
              "user": {
                "$ref": "#/components/schemas/UserObject"
              }
            }
          }
        }
      },
      "LoginDto": {
        "type": "object",
        "required": [
          "email",
          "password"
        ],
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "example": "ada@example.com"
          },
          "password": {
            "type": "string",
            "example": "mypassword123"
          }
        }
      },
      "RefreshTokenDto": {
        "type": "object",
        "properties": {
          "refreshToken": {
            "type": "string",
            "description": "Optional. If omitted the server reads the `refreshToken` httpOnly cookie instead. Providing it in the body takes precedence over the cookie.\n",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          }
        }
      },
      "AuthTokenResponse": {
        "type": "object",
        "description": "Returned by login, verify-email, and refresh endpoints",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Login successful"
          },
          "data": {
            "type": "object",
            "properties": {
              "accessToken": {
                "type": "string",
                "description": "Short-lived JWT — send as: Authorization: Bearer <token>",
                "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              },
              "refreshToken": {
                "type": "string",
                "description": "Long-lived token — also set as httpOnly cookie automatically",
                "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              },
              "isFirstLogin": {
                "type": "boolean",
                "description": "Only present on login and verify-email responses"
              },
              "user": {
                "$ref": "#/components/schemas/UserObject"
              }
            }
          }
        }
      },
      "VerifyEmailDto": {
        "type": "object",
        "required": [
          "email",
          "otp"
        ],
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          },
          "otp": {
            "type": "string",
            "minLength": 6,
            "maxLength": 6,
            "example": "482916"
          }
        }
      },
      "ResendOTPDto": {
        "type": "object",
        "required": [
          "email"
        ],
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          }
        }
      },
      "UserObject": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "roles": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "FAN",
                "CELEBRITY",
                "ADMIN"
              ]
            }
          },
          "isEmailVerified": {
            "type": "boolean"
          },
          "isFirstLogin": {
            "type": "boolean"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CreateBookingDto": {
        "type": "object",
        "required": [
          "celebrityId",
          "timeSessionId"
        ],
        "properties": {
          "celebrityId": {
            "type": "string",
            "example": "64a1f2b3c4d5e6f7a8b9c0d1"
          },
          "timeSessionId": {
            "type": "string",
            "example": "64a1f2b3c4d5e6f7a8b9c0d2"
          },
          "message": {
            "type": "string",
            "description": "Why you're a fan and what you'd like to discuss",
            "example": "I've followed your career since 2018 and would love to discuss your creative process."
          },
          "telegramUsername": {
            "type": "string",
            "description": "Optional Telegram handle for seamless chat integration",
            "example": "@ada_okafor"
          }
        }
      },
      "BookingObject": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "fanId": {
            "type": "object",
            "description": "Populated Fan"
          },
          "celebrityId": {
            "type": "object",
            "description": "Populated Celebrity"
          },
          "timeSessionId": {
            "type": "object",
            "description": "Populated TimeSession"
          },
          "message": {
            "type": "string"
          },
          "telegramUsername": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "PENDING",
              "CONFIRMED",
              "REJECTED",
              "CANCELLED"
            ]
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ApplyCelebrityDto": {
        "type": "object",
        "required": [
          "name",
          "profession",
          "category",
          "bookingPrice"
        ],
        "properties": {
          "name": {
            "type": "string",
            "example": "Burna Boy"
          },
          "profession": {
            "type": "string",
            "example": "Singer & Songwriter"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ],
            "example": "MUSIC_ARTISTE"
          },
          "bio": {
            "type": "string",
            "example": "Grammy-winning Afrobeats artist from Nigeria."
          },
          "bookingPrice": {
            "type": "number",
            "minimum": 0,
            "example": 5000
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "Afrobeats",
              "Reggae",
              "Fashion"
            ]
          }
        }
      },
      "CreateCelebrityDto": {
        "type": "object",
        "required": [
          "name",
          "profession",
          "category",
          "bookingPrice"
        ],
        "properties": {
          "name": {
            "type": "string",
            "example": "Burna Boy"
          },
          "profession": {
            "type": "string",
            "example": "Singer & Songwriter"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ],
            "example": "MUSIC_ARTISTE"
          },
          "userId": {
            "type": "string",
            "nullable": true,
            "description": "MongoDB ObjectId of the linked user account (optional)",
            "example": "64a1f2b3c4d5e6f7a8b9c0d1"
          },
          "status": {
            "type": "string",
            "enum": [
              "AVAILABLE",
              "LIMITED",
              "UNAVAILABLE"
            ],
            "default": "AVAILABLE"
          },
          "bio": {
            "type": "string",
            "example": "Grammy-winning Afrobeats artist from Nigeria."
          },
          "bookingPrice": {
            "type": "number",
            "minimum": 0,
            "example": 5000
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "Afrobeats",
              "Reggae",
              "Fashion"
            ]
          }
        }
      },
      "UpdateCelebrityDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "profession": {
            "type": "string"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ]
          },
          "userId": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "string",
            "enum": [
              "AVAILABLE",
              "LIMITED",
              "UNAVAILABLE"
            ]
          },
          "bio": {
            "type": "string"
          },
          "bookingPrice": {
            "type": "number",
            "minimum": 0
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "RejectCelebrityDto": {
        "type": "object",
        "properties": {
          "reason": {
            "type": "string",
            "example": "Insufficient profile information provided."
          }
        }
      },
      "CelebrityObject": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "profession": {
            "type": "string"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ]
          },
          "userId": {
            "type": "object",
            "nullable": true,
            "description": "Populated User object if linked; null otherwise"
          },
          "status": {
            "type": "string",
            "enum": [
              "AVAILABLE",
              "LIMITED",
              "UNAVAILABLE"
            ]
          },
          "approvalStatus": {
            "type": "string",
            "enum": [
              "APPROVED",
              "PENDING",
              "REJECTED"
            ]
          },
          "rejectionReason": {
            "type": "string",
            "nullable": true
          },
          "bio": {
            "type": "string"
          },
          "bookingPrice": {
            "type": "number"
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CelebrityResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/CelebrityObject"
          }
        }
      },
      "PaginatedCelebrityResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/CelebrityObject"
                }
              },
              "page": {
                "type": "integer",
                "example": 1
              },
              "limit": {
                "type": "integer",
                "example": 10
              },
              "total": {
                "type": "integer",
                "example": 42
              },
              "totalPages": {
                "type": "integer",
                "example": 5
              }
            }
          }
        }
      },
      "CreateChatDto": {
        "type": "object",
        "required": [
          "fanId",
          "celebrityId",
          "telegramUsername"
        ],
        "properties": {
          "fanId": {
            "type": "string",
            "example": "64a1f2b3c4d5e6f7a8b9c0d1"
          },
          "celebrityId": {
            "type": "string",
            "example": "64a1f2b3c4d5e6f7a8b9c0d2"
          },
          "bookingId": {
            "type": "string",
            "description": "Optional linked booking",
            "example": "64a1f2b3c4d5e6f7a8b9c0d3"
          },
          "telegramUsername": {
            "type": "string",
            "example": "@ada_okafor"
          }
        }
      },
      "UpdateChatDto": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "ACTIVE",
              "INACTIVE"
            ]
          },
          "telegramUsername": {
            "type": "string"
          }
        }
      },
      "ChatObject": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "fanId": {
            "type": "object",
            "description": "Populated Fan"
          },
          "celebrityId": {
            "type": "object",
            "description": "Populated Celebrity"
          },
          "bookingId": {
            "type": "string"
          },
          "telegramUsername": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "ACTIVE",
              "INACTIVE"
            ]
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CreateFanReviewDto": {
        "type": "object",
        "required": [
          "celebrityId",
          "rating"
        ],
        "properties": {
          "celebrityId": {
            "type": "string",
            "example": "64a1f2b3c4d5e6f7a8b9c0d1"
          },
          "bookingId": {
            "type": "string",
            "description": "Optional linked booking"
          },
          "rating": {
            "type": "number",
            "minimum": 0,
            "maximum": 5,
            "example": 4.5
          },
          "comment": {
            "type": "string",
            "example": "Amazing session, very engaging and insightful!"
          }
        }
      },
      "UpdateFanReviewDto": {
        "type": "object",
        "properties": {
          "rating": {
            "type": "number",
            "minimum": 0,
            "maximum": 5
          },
          "comment": {
            "type": "string"
          }
        }
      },
      "FanReviewObject": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "fanId": {
            "type": "object",
            "description": "Populated Fan"
          },
          "celebrityId": {
            "type": "object",
            "description": "Populated Celebrity"
          },
          "bookingId": {
            "type": "string"
          },
          "rating": {
            "type": "number"
          },
          "comment": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CreateFanDto": {
        "type": "object",
        "properties": {
          "bio": {
            "type": "string",
            "example": "Huge fan of Afrobeats and basketball."
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "Afrobeats",
              "NBA",
              "Tech"
            ]
          }
        }
      },
      "UpdateFanDto": {
        "type": "object",
        "properties": {
          "bio": {
            "type": "string"
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "FanResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Fan profile retrieved successfully"
          },
          "data": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string"
              },
              "userId": {
                "type": "object",
                "description": "Populated user object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "roles": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "enum": [
                        "FAN",
                        "CELEBRITY",
                        "ADMIN"
                      ]
                    }
                  }
                }
              },
              "bio": {
                "type": "string"
              },
              "interests": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "createdAt": {
                "type": "string",
                "format": "date-time"
              },
              "updatedAt": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        }
      },
      "PaginatedFanResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/FanResponse/properties/data"
                }
              },
              "page": {
                "type": "integer",
                "example": 1
              },
              "limit": {
                "type": "integer",
                "example": 10
              },
              "total": {
                "type": "integer",
                "example": 100
              },
              "totalPages": {
                "type": "integer",
                "example": 10
              }
            }
          }
        }
      },
      "CreateTimeSessionDto": {
        "type": "object",
        "required": [
          "celebrityId",
          "date",
          "startTime",
          "endTime"
        ],
        "properties": {
          "celebrityId": {
            "type": "string",
            "description": "Celebrity MongoDB ObjectId",
            "example": "64a1f2b3c4d5e6f7a8b9c0d1"
          },
          "date": {
            "type": "string",
            "format": "date",
            "example": "2026-06-15"
          },
          "startTime": {
            "type": "string",
            "example": "10:00"
          },
          "endTime": {
            "type": "string",
            "example": "11:00"
          }
        }
      },
      "UpdateTimeSessionDto": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "startTime": {
            "type": "string"
          },
          "endTime": {
            "type": "string"
          }
        }
      },
      "TimeSessionObject": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "celebrityId": {
            "type": "object",
            "description": "Populated Celebrity"
          },
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "startTime": {
            "type": "string"
          },
          "endTime": {
            "type": "string"
          },
          "isBooked": {
            "type": "boolean"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "UpdateMyProfileDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Ada Okafor"
          },
          "phoneNumber": {
            "type": "string",
            "example": "+2348012345678"
          },
          "country": {
            "type": "string",
            "example": "Nigeria"
          },
          "bio": {
            "type": "string",
            "example": "Software engineer and music lover."
          },
          "profilePicture": {
            "type": "string",
            "format": "uri",
            "example": "https://cdn.example.com/avatars/ada.jpg"
          }
        }
      },
      "UserProfileResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "roles": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "FAN",
                    "CELEBRITY",
                    "ADMIN"
                  ]
                }
              },
              "phoneNumber": {
                "type": "string"
              },
              "country": {
                "type": "string"
              },
              "bio": {
                "type": "string"
              },
              "profilePicture": {
                "type": "string"
              },
              "isEmailVerified": {
                "type": "boolean"
              },
              "isFirstLogin": {
                "type": "boolean"
              },
              "createdAt": {
                "type": "string",
                "format": "date-time"
              },
              "updatedAt": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/auth/register/fan": {
      "post": {
        "summary": "Register as a Fan",
        "description": "**Public.** Creates a new user account with the `FAN` role. A 6-digit OTP is emailed for verification. No tokens are returned until the email is verified via `POST /auth/verify-email`.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Registration successful — OTP sent to email",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation error or email already in use"
          }
        }
      }
    },
    "/auth/register/celebrity": {
      "post": {
        "summary": "Register as a Celebrity",
        "description": "**Public.** Creates a new user account with the `CELEBRITY` role. A 6-digit OTP is emailed for verification. After verifying your email, submit your celebrity profile via `POST /celebrities/apply` to go through admin approval before your profile is publicly visible.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Registration successful — OTP sent to email",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation error or email already in use"
          }
        }
      }
    },
    "/auth/register/admin": {
      "post": {
        "summary": "Register a new Admin",
        "description": "**Private — Admin only.** Creates a new user account with the `ADMIN` role. Only an authenticated admin can call this endpoint — this prevents self-elevation by regular users. The first admin is always seeded via the server-side seed script (`npm run seedAdmin`). A 6-digit OTP is emailed to the new admin for verification. No tokens are returned until they verify via `POST /auth/verify-email`.\n",
        "tags": [
          "Auth"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Admin registered — OTP sent to email",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation error or email already in use"
          },
          "401": {
            "description": "Not authenticated"
          },
          "403": {
            "description": "Caller is not an admin"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login",
        "description": "**Public.** Authenticates the user. Returns both tokens in the response body (`accessToken`, `refreshToken`) **and** sets the refresh token as an httpOnly cookie. Works for all roles.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login successful — both tokens returned in body; refresh token also set as httpOnly cookie",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthTokenResponse"
                }
              }
            }
          },
          "401": {
            "description": "Invalid credentials"
          },
          "403": {
            "description": "Email not verified (fresh OTP auto-sent)"
          }
        }
      }
    },
    "/auth/verify-email": {
      "post": {
        "summary": "Verify email with OTP",
        "description": "**Public.** Submits the 6-digit OTP sent to the user's email. On success, issues both tokens in the response body (`accessToken`, `refreshToken`) **and** sets the refresh token as an httpOnly cookie. This is the only path to receive auth tokens after registration.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VerifyEmailDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Email verified — both tokens returned in body; refresh token also set as httpOnly cookie",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthTokenResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid or expired OTP"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/auth/resend-verification": {
      "post": {
        "summary": "Resend email verification OTP",
        "description": "**Public.** Generates a fresh OTP and emails it. Any prior OTP is invalidated. Only works for unverified accounts.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResendOTPDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "New OTP sent"
          },
          "400": {
            "description": "Email already verified"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "summary": "Refresh access token",
        "description": "**Public.** Accepts the refresh token either as a JSON body field (`refreshToken`) **or** from the `refreshToken` httpOnly cookie set at login — whichever is present. Body takes precedence over the cookie. Returns a new rotated `accessToken` and `refreshToken` in the response body, and also rotates the cookie.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokenDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Tokens rotated — both returned in body; refresh token cookie also updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthTokenResponse"
                }
              }
            }
          },
          "401": {
            "description": "No refresh token provided, or token is invalid / expired"
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "Logout",
        "description": "**Public.** Clears the refresh token cookie.",
        "tags": [
          "Auth"
        ],
        "security": [],
        "responses": {
          "200": {
            "description": "Logged out successfully"
          }
        }
      }
    },
    "/bookings/my": {
      "get": {
        "summary": "Get my bookings",
        "description": "**Private — Any authenticated user.** Returns all bookings made by the current user.",
        "tags": [
          "Bookings"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "PENDING",
                "CONFIRMED",
                "REJECTED",
                "CANCELLED"
              ]
            }
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of your bookings"
          }
        }
      }
    },
    "/bookings": {
      "post": {
        "summary": "Create a booking",
        "description": "**Private — Any authenticated user.** Books a specific time session with a celebrity. The slot is locked immediately on creation (status: PENDING). An admin must confirm or reject it.\n",
        "tags": [
          "Bookings"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateBookingDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Booking created (PENDING)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingObject"
                }
              }
            }
          },
          "400": {
            "description": "Time slot already booked or validation error"
          }
        }
      },
      "get": {
        "summary": "Get all bookings",
        "description": "**Private — Admin only.**",
        "tags": [
          "Bookings"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "PENDING",
                "CONFIRMED",
                "REJECTED",
                "CANCELLED"
              ]
            }
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of all bookings"
          }
        }
      }
    },
    "/bookings/{id}/cancel": {
      "patch": {
        "summary": "Cancel a booking",
        "description": "**Private — Booking owner only.** Only PENDING bookings can be cancelled.",
        "tags": [
          "Bookings"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Booking cancelled — time slot released"
          },
          "400": {
            "description": "Booking already cancelled or confirmed"
          },
          "403": {
            "description": "Not your booking"
          }
        }
      }
    },
    "/bookings/{id}": {
      "get": {
        "summary": "Get booking by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Bookings"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Booking found"
          },
          "404": {
            "description": "Booking not found"
          }
        }
      }
    },
    "/bookings/{id}/confirm": {
      "patch": {
        "summary": "Confirm a booking",
        "description": "**Private — Admin only.** Confirms a PENDING booking. If the booking has a `telegramUsername`, a Chat record is automatically created.\n",
        "tags": [
          "Bookings"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Booking confirmed — chat auto-created if telegramUsername present"
          },
          "400": {
            "description": "Only pending bookings can be confirmed"
          }
        }
      }
    },
    "/bookings/{id}/reject": {
      "patch": {
        "summary": "Reject a booking",
        "description": "**Private — Admin only.** Rejects a PENDING booking and releases the time slot.",
        "tags": [
          "Bookings"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Booking rejected — time slot released"
          },
          "400": {
            "description": "Only pending bookings can be rejected"
          }
        }
      }
    },
    "/celebrities": {
      "get": {
        "summary": "Get all celebrities",
        "description": "**Public** (admins see all approval statuses; public sees only APPROVED profiles). Supports filtering by `category`, `status` (exact match) and partial text search on `name` and `interests`.\n",
        "tags": [
          "Celebrities"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "schema": {
              "type": "string"
            },
            "description": "Partial case-insensitive name search"
          },
          {
            "in": "query",
            "name": "interest",
            "schema": {
              "type": "string"
            },
            "description": "Partial case-insensitive keyword search against interests array"
          },
          {
            "in": "query",
            "name": "category",
            "schema": {
              "type": "string",
              "enum": [
                "MUSIC_ARTISTE",
                "FILM_ACTOR",
                "PROFESSIONAL_ATHLETE",
                "TECH_ENTREPRENEUR"
              ]
            }
          },
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "AVAILABLE",
                "LIMITED",
                "UNAVAILABLE"
              ]
            }
          },
          {
            "in": "query",
            "name": "approvalStatus",
            "schema": {
              "type": "string",
              "enum": [
                "APPROVED",
                "PENDING",
                "REJECTED"
              ]
            },
            "description": "Admin only — filter by approval status"
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          },
          {
            "in": "query",
            "name": "sort",
            "schema": {
              "type": "string"
            },
            "description": "Comma-separated sort fields. Prefix with - for descending. Default: -createdAt"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of celebrities",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginatedCelebrityResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a celebrity profile (Admin)",
        "description": "**Private — Admin only.** Creates an admin-verified celebrity profile directly. Profile is `APPROVED` by default. Supply `userId` to link a registered user account.\n",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Celebrity created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "403": {
            "description": "Insufficient permissions"
          }
        }
      }
    },
    "/celebrities/{id}": {
      "get": {
        "summary": "Get celebrity by ID",
        "description": "**Public.** Returns a single celebrity profile with the linked user populated. Non-approved profiles are hidden from public — only the owner or an admin can view them.\n",
        "tags": [
          "Celebrities"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Celebrity found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      },
      "patch": {
        "summary": "Update a celebrity profile (Admin)",
        "description": "**Private — Admin only.** All fields are optional.",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Celebrity updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      },
      "delete": {
        "summary": "Delete a celebrity profile (Admin)",
        "description": "**Private — Admin only.**",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Celebrity deleted"
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      }
    },
    "/celebrities/apply": {
      "post": {
        "summary": "Apply as a celebrity",
        "description": "**Private — Any authenticated user.** Submits a celebrity profile application. The profile is created with `approvalStatus: PENDING` and is not publicly visible until an admin approves it via `PATCH /celebrities/{id}/approve`. Each user can only have one celebrity profile.\n",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ApplyCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Application submitted — pending admin approval",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "400": {
            "description": "You already have a celebrity profile"
          },
          "401": {
            "description": "Not authenticated"
          }
        }
      }
    },
    "/celebrities/{id}/approve": {
      "patch": {
        "summary": "Approve a celebrity application",
        "description": "**Private — Admin only.** Moves the profile from PENDING to APPROVED, making it publicly visible.",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Profile approved",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "400": {
            "description": "Profile is already approved"
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      }
    },
    "/celebrities/{id}/reject": {
      "patch": {
        "summary": "Reject a celebrity application",
        "description": "**Private — Admin only.** Rejects a PENDING profile with an optional reason.",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RejectCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Profile rejected",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "400": {
            "description": "Only pending profiles can be rejected"
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      }
    },
    "/chats/my": {
      "get": {
        "summary": "Get my chats",
        "description": "**Private — Any authenticated user.** Returns chats where the current user is the fan.",
        "tags": [
          "Chats"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "ACTIVE",
                "INACTIVE"
              ]
            }
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of your chats"
          }
        }
      }
    },
    "/chats": {
      "get": {
        "summary": "Get all chats",
        "description": "**Private — Admin only.**",
        "tags": [
          "Chats"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "ACTIVE",
                "INACTIVE"
              ]
            }
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of all chats"
          }
        }
      },
      "post": {
        "summary": "Create a chat manually",
        "description": "**Private — Admin only.** Manually creates a chat record. Chats are also auto-created when a booking with a `telegramUsername` is confirmed.\n",
        "tags": [
          "Chats"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateChatDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Chat created"
          }
        }
      }
    },
    "/chats/{id}": {
      "get": {
        "summary": "Get chat by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Chats"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Chat found"
          },
          "404": {
            "description": "Chat not found"
          }
        }
      },
      "patch": {
        "summary": "Update chat status or telegram username",
        "description": "**Private — Admin only.**",
        "tags": [
          "Chats"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateChatDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Chat updated"
          }
        }
      },
      "delete": {
        "summary": "Delete a chat",
        "description": "**Private — Admin only.**",
        "tags": [
          "Chats"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Chat deleted"
          }
        }
      }
    },
    "/dashboard": {
      "get": {
        "summary": "Get dashboard statistics",
        "description": "**Private — Admin only.** Returns aggregated platform stats: total/pending/confirmed/rejected/cancelled bookings and active chat count with recent active chat details.\n",
        "tags": [
          "Dashboard"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Dashboard statistics",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DashboardResponse"
                }
              }
            }
          }
        }
      }
    },
    "/reviews/celebrity/{celebrityId}": {
      "get": {
        "summary": "Get reviews for a celebrity",
        "description": "**Public.** Returns all reviews for a specific celebrity.",
        "tags": [
          "FanReviews"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "celebrityId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of reviews"
          }
        }
      }
    },
    "/reviews": {
      "post": {
        "summary": "Submit a review",
        "description": "**Private — Any authenticated user.** One review per fan per celebrity.",
        "tags": [
          "FanReviews"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateFanReviewDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Review submitted"
          },
          "400": {
            "description": "Already reviewed this celebrity"
          }
        }
      },
      "get": {
        "summary": "Get all reviews",
        "description": "**Private — Admin only.**",
        "tags": [
          "FanReviews"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of all reviews"
          }
        }
      }
    },
    "/reviews/{id}": {
      "patch": {
        "summary": "Update your review",
        "description": "**Private — Review owner only.**",
        "tags": [
          "FanReviews"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateFanReviewDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Review updated"
          },
          "403": {
            "description": "Not your review"
          }
        }
      },
      "delete": {
        "summary": "Delete a review",
        "description": "**Private — Review owner or Admin.**",
        "tags": [
          "FanReviews"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Review deleted"
          },
          "403": {
            "description": "Not your review"
          }
        }
      },
      "get": {
        "summary": "Get review by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "FanReviews"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Review found"
          },
          "404": {
            "description": "Review not found"
          }
        }
      }
    },
    "/fans/me": {
      "get": {
        "summary": "Get my fan profile",
        "description": "**Private — Any authenticated user.** Returns the fan profile linked to the current user.",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Fan profile found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan profile not found"
          }
        }
      },
      "patch": {
        "summary": "Update my fan profile",
        "description": "**Private — Any authenticated user.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateFanDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Fan profile updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan profile not found"
          }
        }
      }
    },
    "/fans": {
      "post": {
        "summary": "Create fan profile",
        "description": "**Private — Any authenticated user.** Creates a fan profile linked to the current user. Each user can only have one fan profile.\n",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateFanDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Fan profile created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "400": {
            "description": "Fan profile already exists for this user"
          }
        }
      },
      "get": {
        "summary": "Get all fan profiles",
        "description": "**Private — Admin only.** Returns a paginated list of all fan profiles with user data populated.",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          },
          {
            "in": "query",
            "name": "sort",
            "schema": {
              "type": "string"
            },
            "description": "Comma-separated sort fields. Prefix with - for descending. Default: -createdAt"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of fans",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginatedFanResponse"
                }
              }
            }
          }
        }
      }
    },
    "/fans/{id}": {
      "get": {
        "summary": "Get fan by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Fan found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan not found"
          }
        }
      },
      "patch": {
        "summary": "Update fan by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateFanDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Fan updated"
          },
          "404": {
            "description": "Fan not found"
          }
        }
      },
      "delete": {
        "summary": "Delete fan by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Fan deleted"
          },
          "404": {
            "description": "Fan not found"
          }
        }
      }
    },
    "/time-sessions/celebrity/{celebrityId}": {
      "get": {
        "summary": "Get available slots for a celebrity",
        "description": "**Public.** Returns only unbooked time sessions for the given celebrity.",
        "tags": [
          "TimeSessions"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "celebrityId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of available time sessions"
          }
        }
      }
    },
    "/time-sessions/{id}": {
      "get": {
        "summary": "Get time session by ID",
        "description": "**Public.**",
        "tags": [
          "TimeSessions"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Time session found"
          },
          "404": {
            "description": "Time session not found"
          }
        }
      },
      "patch": {
        "summary": "Update a time session",
        "description": "**Private — Admin only.** Cannot edit a session that is already booked.",
        "tags": [
          "TimeSessions"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateTimeSessionDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Time session updated"
          },
          "400": {
            "description": "Cannot edit a booked session"
          },
          "404": {
            "description": "Time session not found"
          }
        }
      },
      "delete": {
        "summary": "Delete a time session",
        "description": "**Private — Admin only.** Cannot delete a session that is already booked.",
        "tags": [
          "TimeSessions"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Time session deleted"
          },
          "400": {
            "description": "Cannot delete a booked session"
          },
          "404": {
            "description": "Time session not found"
          }
        }
      }
    },
    "/time-sessions": {
      "get": {
        "summary": "Get all time sessions",
        "description": "**Private — Admin only.** Returns all time sessions with optional filtering.",
        "tags": [
          "TimeSessions"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "celebrityId",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "isBooked",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of time sessions"
          }
        }
      },
      "post": {
        "summary": "Create a time session",
        "description": "**Private — Admin only.** Creates an available time slot for a celebrity.",
        "tags": [
          "TimeSessions"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateTimeSessionDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Time session created"
          },
          "400": {
            "description": "Validation error"
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "summary": "Get my profile",
        "description": "**Private — Any authenticated user.** Returns the current user's full profile.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Profile retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserProfileResponse"
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update my profile",
        "description": "**Private — Any authenticated user.** Updates name, phone, country, bio, or profilePicture. Cannot change email, password, or roles here.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateMyProfileDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Profile updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserProfileResponse"
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "Get all users",
        "description": "**Private — Admin only.** Returns a paginated list of all user accounts.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "search",
            "schema": {
              "type": "string"
            },
            "description": "Search by name or email"
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of users"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Get user by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User found"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "patch": {
        "summary": "Update user",
        "description": "**Private — Admin only.**",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "roles": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "enum": [
                        "FAN",
                        "CELEBRITY",
                        "ADMIN"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User updated"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "delete": {
        "summary": "Delete user",
        "description": "**Private — Admin only.**",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User deleted"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Auth",
      "description": "Authentication — registration, login, email verification, token management"
    },
    {
      "name": "Bookings",
      "description": "Fan session bookings with celebrities"
    },
    {
      "name": "Celebrities",
      "description": "Celebrity profiles — public browsing, self-application, admin management"
    },
    {
      "name": "Chats",
      "description": "Telegram chat integration records"
    },
    {
      "name": "Dashboard",
      "description": "Platform-wide statistics for admins"
    },
    {
      "name": "FanReviews",
      "description": "Fan ratings and reviews for celebrities"
    },
    {
      "name": "Fans",
      "description": "Fan profile management"
    },
    {
      "name": "TimeSessions",
      "description": "Celebrity availability time slots"
    },
    {
      "name": "Users",
      "description": "User account management (Admin only)"
    }
  ]
} as object;
