// Auto-generated by: npm run generate-swagger
// Do not edit manually — re-run the script whenever JSDoc annotations change.
/* eslint-disable */
export default {
  "openapi": "3.0.0",
  "info": {
    "title": "Artiste Meetup API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/api/v1"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "RegisterDto": {
        "type": "object",
        "required": [
          "name",
          "email",
          "password"
        ],
        "properties": {
          "name": {
            "type": "string",
            "example": "Ada Okafor"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "ada@example.com"
          },
          "password": {
            "type": "string",
            "minLength": 6,
            "example": "mypassword123"
          }
        }
      },
      "RegisterResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 201
          },
          "message": {
            "type": "string",
            "example": "Registration successful. Check your email for a 6-digit OTP."
          },
          "data": {
            "type": "object",
            "properties": {
              "user": {
                "$ref": "#/components/schemas/UserObject"
              }
            }
          }
        }
      },
      "LoginDto": {
        "type": "object",
        "required": [
          "email",
          "password"
        ],
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "example": "ada@example.com"
          },
          "password": {
            "type": "string",
            "example": "mypassword123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Login successful"
          },
          "data": {
            "type": "object",
            "properties": {
              "accessToken": {
                "type": "string",
                "description": "JWT bearer token — include as Authorization header"
              },
              "isFirstLogin": {
                "type": "boolean"
              },
              "user": {
                "$ref": "#/components/schemas/UserObject"
              }
            }
          }
        }
      },
      "VerifyEmailDto": {
        "type": "object",
        "required": [
          "email",
          "otp"
        ],
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          },
          "otp": {
            "type": "string",
            "minLength": 6,
            "maxLength": 6,
            "example": "482916"
          }
        }
      },
      "ResendOTPDto": {
        "type": "object",
        "required": [
          "email"
        ],
        "properties": {
          "email": {
            "type": "string",
            "format": "email"
          }
        }
      },
      "UserObject": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "roles": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "FAN",
                "CELEBRITY",
                "ADMIN"
              ]
            }
          },
          "isEmailVerified": {
            "type": "boolean"
          },
          "isFirstLogin": {
            "type": "boolean"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "ApplyCelebrityDto": {
        "type": "object",
        "required": [
          "name",
          "profession",
          "category",
          "bookingPrice"
        ],
        "properties": {
          "name": {
            "type": "string",
            "example": "Burna Boy"
          },
          "profession": {
            "type": "string",
            "example": "Singer & Songwriter"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ],
            "example": "MUSIC_ARTISTE"
          },
          "bio": {
            "type": "string",
            "example": "Grammy-winning Afrobeats artist from Nigeria."
          },
          "bookingPrice": {
            "type": "number",
            "minimum": 0,
            "example": 5000
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "Afrobeats",
              "Reggae",
              "Fashion"
            ]
          }
        }
      },
      "CreateCelebrityDto": {
        "type": "object",
        "required": [
          "name",
          "profession",
          "category",
          "bookingPrice"
        ],
        "properties": {
          "name": {
            "type": "string",
            "example": "Burna Boy"
          },
          "profession": {
            "type": "string",
            "example": "Singer & Songwriter"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ],
            "example": "MUSIC_ARTISTE"
          },
          "userId": {
            "type": "string",
            "nullable": true,
            "description": "MongoDB ObjectId of the linked user account (optional)",
            "example": "64a1f2b3c4d5e6f7a8b9c0d1"
          },
          "status": {
            "type": "string",
            "enum": [
              "AVAILABLE",
              "LIMITED",
              "UNAVAILABLE"
            ],
            "default": "AVAILABLE"
          },
          "bio": {
            "type": "string",
            "example": "Grammy-winning Afrobeats artist from Nigeria."
          },
          "bookingPrice": {
            "type": "number",
            "minimum": 0,
            "example": 5000
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "Afrobeats",
              "Reggae",
              "Fashion"
            ]
          }
        }
      },
      "UpdateCelebrityDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "profession": {
            "type": "string"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ]
          },
          "userId": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "string",
            "enum": [
              "AVAILABLE",
              "LIMITED",
              "UNAVAILABLE"
            ]
          },
          "bio": {
            "type": "string"
          },
          "bookingPrice": {
            "type": "number",
            "minimum": 0
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "RejectCelebrityDto": {
        "type": "object",
        "properties": {
          "reason": {
            "type": "string",
            "example": "Insufficient profile information provided."
          }
        }
      },
      "CelebrityObject": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "profession": {
            "type": "string"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ]
          },
          "userId": {
            "type": "object",
            "nullable": true,
            "description": "Populated User object if linked; null otherwise"
          },
          "status": {
            "type": "string",
            "enum": [
              "AVAILABLE",
              "LIMITED",
              "UNAVAILABLE"
            ]
          },
          "approvalStatus": {
            "type": "string",
            "enum": [
              "APPROVED",
              "PENDING",
              "REJECTED"
            ]
          },
          "rejectionReason": {
            "type": "string",
            "nullable": true
          },
          "bio": {
            "type": "string"
          },
          "bookingPrice": {
            "type": "number"
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "CelebrityResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/CelebrityObject"
          }
        }
      },
      "PaginatedCelebrityResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/CelebrityObject"
                }
              },
              "page": {
                "type": "integer",
                "example": 1
              },
              "limit": {
                "type": "integer",
                "example": 10
              },
              "total": {
                "type": "integer",
                "example": 42
              },
              "totalPages": {
                "type": "integer",
                "example": 5
              }
            }
          }
        }
      },
      "CreateFanDto": {
        "type": "object",
        "properties": {
          "bio": {
            "type": "string",
            "example": "Huge fan of Afrobeats and basketball."
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "Afrobeats",
              "NBA",
              "Tech"
            ]
          }
        }
      },
      "UpdateFanDto": {
        "type": "object",
        "properties": {
          "bio": {
            "type": "string"
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "FanResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Fan profile retrieved successfully"
          },
          "data": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string"
              },
              "userId": {
                "type": "object",
                "description": "Populated user object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string"
                  }
                }
              },
              "bio": {
                "type": "string"
              },
              "interests": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "createdAt": {
                "type": "string",
                "format": "date-time"
              },
              "updatedAt": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        }
      },
      "PaginatedFanResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/FanResponse/properties/data"
                }
              },
              "page": {
                "type": "integer",
                "example": 1
              },
              "limit": {
                "type": "integer",
                "example": 10
              },
              "total": {
                "type": "integer",
                "example": 100
              },
              "totalPages": {
                "type": "integer",
                "example": 10
              }
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/auth/register/fan": {
      "post": {
        "summary": "Register as a Fan",
        "description": "**Public.** Creates a new user account with the `FAN` role. A 6-digit OTP is emailed for verification. No tokens are returned until the email is verified via `POST /auth/verify-email`.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Registration successful — OTP sent to email",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation error or email already in use"
          }
        }
      }
    },
    "/auth/register/celebrity": {
      "post": {
        "summary": "Register as a Celebrity",
        "description": "**Public.** Creates a new user account with the `CELEBRITY` role. A 6-digit OTP is emailed for verification. After verifying your email, submit your celebrity profile via `POST /celebrities/apply` to go through admin approval before your profile is publicly visible.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Registration successful — OTP sent to email",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation error or email already in use"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login",
        "description": "**Public.** Authenticates the user and returns an access token in the response body plus a `refreshToken` httpOnly cookie. Works for all roles.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Invalid credentials"
          },
          "403": {
            "description": "Email not verified (fresh OTP auto-sent)"
          }
        }
      }
    },
    "/auth/verify-email": {
      "post": {
        "summary": "Verify email with OTP",
        "description": "**Public.** Submits the 6-digit OTP sent to the user's email. On success, issues an access token in the body and sets the refresh token as an httpOnly cookie. This is the only path to receive auth tokens after registration.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VerifyEmailDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Email verified — access token returned, refresh cookie set",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid or expired OTP"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/auth/resend-verification": {
      "post": {
        "summary": "Resend email verification OTP",
        "description": "**Public.** Generates a fresh OTP and emails it. Any prior OTP is invalidated. Only works for unverified accounts.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResendOTPDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "New OTP sent"
          },
          "400": {
            "description": "Email already verified"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "summary": "Refresh access token",
        "description": "**Public.** Reads the `refreshToken` httpOnly cookie set at login. No request body required — the browser sends the cookie automatically. Returns a new access token and rotates the refresh token cookie.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "responses": {
          "200": {
            "description": "Token refreshed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid refresh token"
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "Logout",
        "description": "**Public.** Clears the refresh token cookie.",
        "tags": [
          "Auth"
        ],
        "security": [],
        "responses": {
          "200": {
            "description": "Logged out successfully"
          }
        }
      }
    },
    "/celebrities": {
      "get": {
        "summary": "Get all celebrities",
        "description": "**Public** (admins see all approval statuses; public sees only APPROVED profiles). Supports filtering by `category`, `status` (exact match) and partial text search on `name` and `interests`.\n",
        "tags": [
          "Celebrities"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "schema": {
              "type": "string"
            },
            "description": "Partial case-insensitive name search"
          },
          {
            "in": "query",
            "name": "interest",
            "schema": {
              "type": "string"
            },
            "description": "Partial case-insensitive keyword search against interests array"
          },
          {
            "in": "query",
            "name": "category",
            "schema": {
              "type": "string",
              "enum": [
                "MUSIC_ARTISTE",
                "FILM_ACTOR",
                "PROFESSIONAL_ATHLETE",
                "TECH_ENTREPRENEUR"
              ]
            }
          },
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "AVAILABLE",
                "LIMITED",
                "UNAVAILABLE"
              ]
            }
          },
          {
            "in": "query",
            "name": "approvalStatus",
            "schema": {
              "type": "string",
              "enum": [
                "APPROVED",
                "PENDING",
                "REJECTED"
              ]
            },
            "description": "Admin only — filter by approval status"
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          },
          {
            "in": "query",
            "name": "sort",
            "schema": {
              "type": "string"
            },
            "description": "Comma-separated sort fields. Prefix with - for descending. Default: -createdAt"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of celebrities",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginatedCelebrityResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a celebrity profile (Admin)",
        "description": "**Private — Admin only.** Creates an admin-verified celebrity profile directly. Profile is `APPROVED` by default. Supply `userId` to link a registered user account.\n",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Celebrity created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "403": {
            "description": "Insufficient permissions"
          }
        }
      }
    },
    "/celebrities/{id}": {
      "get": {
        "summary": "Get celebrity by ID",
        "description": "**Public.** Returns a single celebrity profile with the linked user populated. Non-approved profiles are hidden from public — only the owner or an admin can view them.\n",
        "tags": [
          "Celebrities"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Celebrity found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      },
      "patch": {
        "summary": "Update a celebrity profile (Admin)",
        "description": "**Private — Admin only.** All fields are optional.",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Celebrity updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      },
      "delete": {
        "summary": "Delete a celebrity profile (Admin)",
        "description": "**Private — Admin only.**",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Celebrity deleted"
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      }
    },
    "/celebrities/apply": {
      "post": {
        "summary": "Apply as a celebrity",
        "description": "**Private — Any authenticated user.** Submits a celebrity profile application. The profile is created with `approvalStatus: PENDING` and is not publicly visible until an admin approves it via `PATCH /celebrities/{id}/approve`. Each user can only have one celebrity profile.\n",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ApplyCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Application submitted — pending admin approval",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "400": {
            "description": "You already have a celebrity profile"
          },
          "401": {
            "description": "Not authenticated"
          }
        }
      }
    },
    "/celebrities/{id}/approve": {
      "patch": {
        "summary": "Approve a celebrity application",
        "description": "**Private — Admin only.** Moves the profile from PENDING to APPROVED, making it publicly visible.",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Profile approved",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "400": {
            "description": "Profile is already approved"
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      }
    },
    "/celebrities/{id}/reject": {
      "patch": {
        "summary": "Reject a celebrity application",
        "description": "**Private — Admin only.** Rejects a PENDING profile with an optional reason.",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RejectCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Profile rejected",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "400": {
            "description": "Only pending profiles can be rejected"
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      }
    },
    "/fans/me": {
      "get": {
        "summary": "Get my fan profile",
        "description": "**Private — Any authenticated user.** Returns the fan profile linked to the current user.",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Fan profile found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan profile not found"
          }
        }
      },
      "patch": {
        "summary": "Update my fan profile",
        "description": "**Private — Any authenticated user.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateFanDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Fan profile updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan profile not found"
          }
        }
      }
    },
    "/fans": {
      "post": {
        "summary": "Create fan profile",
        "description": "**Private — Any authenticated user.** Creates a fan profile linked to the current user. Each user can only have one fan profile.\n",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateFanDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Fan profile created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "400": {
            "description": "Fan profile already exists for this user"
          }
        }
      },
      "get": {
        "summary": "Get all fan profiles",
        "description": "**Private — Admin only.** Returns a paginated list of all fan profiles with user data populated.",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          },
          {
            "in": "query",
            "name": "sort",
            "schema": {
              "type": "string"
            },
            "description": "Comma-separated sort fields. Prefix with - for descending. Default: -createdAt"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of fans",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginatedFanResponse"
                }
              }
            }
          }
        }
      }
    },
    "/fans/{id}": {
      "get": {
        "summary": "Get fan by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Fan found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan not found"
          }
        }
      },
      "patch": {
        "summary": "Update fan by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateFanDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Fan updated"
          },
          "404": {
            "description": "Fan not found"
          }
        }
      },
      "delete": {
        "summary": "Delete fan by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Fan deleted"
          },
          "404": {
            "description": "Fan not found"
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "Get all users",
        "description": "**Private — Admin only.** Returns a paginated list of all user accounts.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "search",
            "schema": {
              "type": "string"
            },
            "description": "Search by name or email"
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of users"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Get user by ID",
        "description": "**Private — Admin only.**",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User found"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "patch": {
        "summary": "Update user",
        "description": "**Private — Admin only.**",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "roles": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "enum": [
                        "FAN",
                        "CELEBRITY",
                        "ADMIN"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User updated"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "delete": {
        "summary": "Delete user",
        "description": "**Private — Admin only.**",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User deleted"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Auth",
      "description": "Authentication — registration, login, email verification, token management"
    },
    {
      "name": "Celebrities",
      "description": "Celebrity profiles — public browsing, self-application, admin management"
    },
    {
      "name": "Fans",
      "description": "Fan profile management"
    },
    {
      "name": "Users",
      "description": "User account management (Admin only)"
    }
  ]
} as object;
