// Auto-generated by: npm run generate-swagger
// Do not edit manually — re-run the script whenever JSDoc annotations change.
/* eslint-disable */
export default {
  "openapi": "3.0.0",
  "info": {
    "title": "Artiste Meetup API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/api/v1"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "CreateCelebrityDto": {
        "type": "object",
        "required": [
          "name",
          "profession",
          "category",
          "bookingPrice"
        ],
        "properties": {
          "name": {
            "type": "string",
            "example": "Burna Boy"
          },
          "profession": {
            "type": "string",
            "example": "Singer & Songwriter"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ],
            "example": "MUSIC_ARTISTE"
          },
          "userId": {
            "type": "string",
            "nullable": true,
            "description": "MongoDB ObjectId of the linked user account (optional)",
            "example": "64a1f2b3c4d5e6f7a8b9c0d1"
          },
          "status": {
            "type": "string",
            "enum": [
              "AVAILABLE",
              "LIMITED",
              "UNAVAILABLE"
            ],
            "default": "AVAILABLE"
          },
          "bio": {
            "type": "string",
            "example": "Grammy-winning Afrobeats artist from Nigeria."
          },
          "bookingPrice": {
            "type": "number",
            "minimum": 0,
            "example": 5000
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "Afrobeats",
              "Reggae",
              "Fashion"
            ]
          }
        }
      },
      "UpdateCelebrityDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "profession": {
            "type": "string"
          },
          "category": {
            "type": "string",
            "enum": [
              "MUSIC_ARTISTE",
              "FILM_ACTOR",
              "PROFESSIONAL_ATHLETE",
              "TECH_ENTREPRENEUR"
            ]
          },
          "userId": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "string",
            "enum": [
              "AVAILABLE",
              "LIMITED",
              "UNAVAILABLE"
            ]
          },
          "bio": {
            "type": "string"
          },
          "bookingPrice": {
            "type": "number",
            "minimum": 0
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "CelebrityResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Celebrity retrieved successfully"
          },
          "data": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "profession": {
                "type": "string"
              },
              "category": {
                "type": "string",
                "enum": [
                  "MUSIC_ARTISTE",
                  "FILM_ACTOR",
                  "PROFESSIONAL_ATHLETE",
                  "TECH_ENTREPRENEUR"
                ]
              },
              "userId": {
                "type": "object",
                "nullable": true,
                "description": "Populated user object if linked"
              },
              "status": {
                "type": "string",
                "enum": [
                  "AVAILABLE",
                  "LIMITED",
                  "UNAVAILABLE"
                ]
              },
              "bio": {
                "type": "string"
              },
              "bookingPrice": {
                "type": "number"
              },
              "interests": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "createdAt": {
                "type": "string",
                "format": "date-time"
              },
              "updatedAt": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        }
      },
      "PaginatedCelebrityResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/CelebrityResponse/properties/data"
                }
              },
              "page": {
                "type": "integer",
                "example": 1
              },
              "limit": {
                "type": "integer",
                "example": 10
              },
              "total": {
                "type": "integer",
                "example": 42
              },
              "totalPages": {
                "type": "integer",
                "example": 5
              }
            }
          }
        }
      },
      "CreateFanDto": {
        "type": "object",
        "properties": {
          "bio": {
            "type": "string",
            "example": "Huge fan of Afrobeats and basketball."
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "Afrobeats",
              "NBA",
              "Tech"
            ]
          }
        }
      },
      "UpdateFanDto": {
        "type": "object",
        "properties": {
          "bio": {
            "type": "string"
          },
          "interests": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "FanResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Fan profile retrieved successfully"
          },
          "data": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string"
              },
              "userId": {
                "type": "object",
                "description": "Populated user object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string"
                  }
                }
              },
              "bio": {
                "type": "string"
              },
              "interests": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "createdAt": {
                "type": "string",
                "format": "date-time"
              },
              "updatedAt": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        }
      },
      "PaginatedFanResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "statusCode": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/FanResponse/properties/data"
                }
              },
              "page": {
                "type": "integer",
                "example": 1
              },
              "limit": {
                "type": "integer",
                "example": 10
              },
              "total": {
                "type": "integer",
                "example": 100
              },
              "totalPages": {
                "type": "integer",
                "example": 10
              }
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "summary": "Register a new user",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email",
                  "password",
                  "role"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string",
                    "enum": [
                      "CUSTOMER",
                      "ARTISTE",
                      "ADMIN"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User registered successfully. A 6-digit OTP has been sent to the provided email address. No tokens are returned until the email is verified via POST /auth/verify-email.\n",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "message": {
                      "type": "string",
                      "example": "Registration successful. Please verify your email."
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "user": {
                          "type": "object"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Validation error or email already in use"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "accessToken": {
                      "type": "string"
                    },
                    "user": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "summary": "Refresh access token",
        "description": "Reads the `refreshToken` from the **httpOnly cookie** set at login. No request body is required — the browser sends the cookie automatically. Returns a new access token and rotates the refresh token cookie.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "responses": {
          "200": {
            "description": "Token refreshed successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "accessToken": {
                      "type": "string"
                    },
                    "user": {
                      "type": "object"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid refresh token cookie"
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "Logout",
        "tags": [
          "Auth"
        ],
        "security": [],
        "responses": {
          "200": {
            "description": "Logout successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/verify-email": {
      "post": {
        "summary": "Verify email with OTP",
        "description": "Submits the 6-digit OTP sent to the user's email during registration (or after a resend request). On success, marks the email as verified, issues an access token in the response body, and sets the refresh token as an httpOnly cookie. This is the only way to receive auth tokens after registration.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "otp"
                ],
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                  },
                  "otp": {
                    "type": "string",
                    "minLength": 6,
                    "maxLength": 6,
                    "example": "482916"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Email verified. Returns access token in body; refresh token is set as an httpOnly cookie.\n",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "message": {
                      "type": "string",
                      "example": "Email verified successfully."
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "accessToken": {
                          "type": "string"
                        },
                        "user": {
                          "type": "object"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid or expired OTP"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/auth/resend-verification": {
      "post": {
        "summary": "Resend email verification OTP",
        "description": "Generates a fresh 6-digit OTP and sends it to the provided email address. Any previously issued OTP is invalidated. Only works for accounts whose email has not yet been verified. Attempting to resend for an already-verified account returns a 400 error.\n",
        "tags": [
          "Auth"
        ],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email"
                ],
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OTP resent successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "message": {
                      "type": "string",
                      "example": "A new verification OTP has been sent to your email."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Email already verified"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/celebrities": {
      "get": {
        "summary": "Get all celebrities",
        "description": "Public endpoint. Returns a paginated list of celebrity profiles. Supports filtering by category and status (exact match), and partial text search on name and interests via dedicated query params.\n",
        "tags": [
          "Celebrities"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "schema": {
              "type": "string"
            },
            "description": "Partial case-insensitive name search"
          },
          {
            "in": "query",
            "name": "interest",
            "schema": {
              "type": "string"
            },
            "description": "Partial case-insensitive keyword search against interests array"
          },
          {
            "in": "query",
            "name": "category",
            "schema": {
              "type": "string",
              "enum": [
                "MUSIC_ARTISTE",
                "FILM_ACTOR",
                "PROFESSIONAL_ATHLETE",
                "TECH_ENTREPRENEUR"
              ]
            },
            "description": "Exact match filter by celebrity category"
          },
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "AVAILABLE",
                "LIMITED",
                "UNAVAILABLE"
              ]
            },
            "description": "Exact match filter by availability status"
          },
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            },
            "description": "Page number for pagination"
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            },
            "description": "Number of results per page"
          },
          {
            "in": "query",
            "name": "sort",
            "schema": {
              "type": "string"
            },
            "description": "Sort fields (comma-separated). Prefix with - for descending. Default: -createdAt"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of celebrities",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginatedCelebrityResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a celebrity profile",
        "description": "**Private — Admin/Super Admin only.** Creates a new celebrity profile. The `userId` field is optional; supply it when the celebrity is also a registered user on the platform.\n",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Celebrity created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation error"
          },
          "401": {
            "description": "Not authenticated"
          },
          "403": {
            "description": "Insufficient permissions"
          }
        }
      }
    },
    "/celebrities/{id}": {
      "get": {
        "summary": "Get celebrity by ID",
        "description": "Public endpoint. Returns a single celebrity profile with linked user populated.",
        "tags": [
          "Celebrities"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Celebrity MongoDB ObjectId"
          }
        ],
        "responses": {
          "200": {
            "description": "Celebrity found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      },
      "patch": {
        "summary": "Update a celebrity profile",
        "description": "**Private — Admin/Super Admin only.** All fields are optional.",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateCelebrityDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Celebrity updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CelebrityResponse"
                }
              }
            }
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      },
      "delete": {
        "summary": "Delete a celebrity profile",
        "description": "**Private — Admin/Super Admin only.**",
        "tags": [
          "Celebrities"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Celebrity deleted"
          },
          "404": {
            "description": "Celebrity not found"
          }
        }
      }
    },
    "/fans/me": {
      "get": {
        "summary": "Get my fan profile",
        "description": "**Private — Any authenticated user.** Returns the fan profile linked to the current user.",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Fan profile found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan profile not found"
          }
        }
      },
      "patch": {
        "summary": "Update my fan profile",
        "description": "**Private — Any authenticated user.** Updates the fan profile of the current user.",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateFanDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Fan profile updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan profile not found"
          }
        }
      }
    },
    "/fans": {
      "post": {
        "summary": "Create fan profile",
        "description": "**Private — Any authenticated user.** Creates a fan profile linked to the current user. Each user can only have one fan profile.\n",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateFanDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Fan profile created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "400": {
            "description": "Fan profile already exists for this user"
          }
        }
      },
      "get": {
        "summary": "Get all fan profiles",
        "description": "**Private — Admin/Super Admin only.** Returns a paginated list of all fan profiles with linked user data populated.\n",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 10
            }
          },
          {
            "in": "query",
            "name": "sort",
            "schema": {
              "type": "string"
            },
            "description": "Sort fields (comma-separated). Prefix with - for descending. Default: -createdAt"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of fans",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaginatedFanResponse"
                }
              }
            }
          }
        }
      }
    },
    "/fans/{id}": {
      "get": {
        "summary": "Get fan by ID",
        "description": "**Private — Admin/Super Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Fan found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FanResponse"
                }
              }
            }
          },
          "404": {
            "description": "Fan not found"
          }
        }
      },
      "patch": {
        "summary": "Update fan by ID",
        "description": "**Private — Admin/Super Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateFanDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Fan updated"
          },
          "404": {
            "description": "Fan not found"
          }
        }
      },
      "delete": {
        "summary": "Delete fan by ID",
        "description": "**Private — Admin/Super Admin only.**",
        "tags": [
          "Fans"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Fan deleted"
          },
          "404": {
            "description": "Fan not found"
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "Get all users",
        "tags": [
          "Users"
        ],
        "responses": {
          "200": {
            "description": "List of users",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "role": {
                            "type": "string"
                          },
                          "createdAt": {
                            "type": "string"
                          },
                          "updatedAt": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Get user by ID",
        "tags": [
          "Users"
        ],
        "responses": {
          "200": {
            "description": "User found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        },
                        "createdAt": {
                          "type": "string"
                        },
                        "updatedAt": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Update user",
        "tags": [
          "Users"
        ],
        "responses": {
          "200": {
            "description": "User updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        },
                        "createdAt": {
                          "type": "string"
                        },
                        "updatedAt": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete user",
        "tags": [
          "Users"
        ],
        "responses": {
          "200": {
            "description": "User deleted successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        },
                        "createdAt": {
                          "type": "string"
                        },
                        "updatedAt": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Celebrities",
      "description": "Celebrity profiles — public browsing, admin management"
    },
    {
      "name": "Fans",
      "description": "Fan profile management"
    }
  ]
} as object;
